CREATE OR REPLACE NONEDITIONABLE FUNCTION SYS.AD_SYNC_DEFAULT_PASSWORD_VERIFY_FUNCTION (
   USERNAME VARCHAR2,
   PASSWORD VARCHAR2,
   OLD_PASSWORD VARCHAR2
) RETURN BOOLEAN IS
--version: 0.0.001
   DIFFER  INTEGER;
   LANG    VARCHAR2(512);
   MESSAGE VARCHAR2(512);
   RET     NUMBER;
BEGIN
 
   -- Get the cur context lang and use utl_lms for messages- Bug 22730089
   LANG := SYS_CONTEXT('userenv', 'lang');
   LANG := SUBSTR(LANG, 1, INSTR(LANG, '_')-1);
   IF NOT ORA_COMPLEXITY_CHECK(PASSWORD, CHARS => 12, UPPERCASE => 1, LOWERCASE => 1, DIGIT => 1, SPECIAL => 1) THEN
      RETURN(FALSE);
   END IF;
 

   -- Check if the password differs from the previous password by at least
   -- 8 characters
   IF OLD_PASSWORD IS NOT NULL THEN
      DIFFER := ORA_STRING_DISTANCE(OLD_PASSWORD, PASSWORD);
      IF DIFFER < 8 THEN
         RET := UTL_LMS.GET_MESSAGE(28211, 'RDBMS', 'ORA', LANG, MESSAGE);
         RAISE_APPLICATION_ERROR(-20000, UTL_LMS.FORMAT_MESSAGE(MESSAGE, 'eight'));
      END IF;
   END IF;

   RETURN(TRUE);
END AD_SYNC_DEFAULT_PASSWORD_VERIFY_FUNCTION;
/
