prompt CREATE OR REPLACE VIEW ad_sync_owner.AD_SYNC_MANAGED_USERS

CREATE OR REPLACE VIEW AD_SYNC_OWNER.AD_SYNC_MANAGED_USERS AS
  SELECT *
    FROM SYS.DBA_USERS
   WHERE USERNAME LIKE AD_SYNC_OWNER.AD_SYNC_TOOLS.GET_PARAM_VALUE('USERNAME_PREFIX')
                       || '%'
   ORDER BY USERNAME;