prompt CREATE TABLE ad_sync_owner.AD_SYNC_USERS_REQUEST_TYPES 
CREATE TABLE ad_sync_owner.AD_SYNC_USERS_REQUEST_TYPES 
(
  ID char(1) NOT NULL 
, REQUEST_TYPE_NAME VARCHAR2(2000) NOT NULL 
, REQUEST_TYPE_DESCRIPTION VARCHAR2(2000) ,
	created_timestamp   TIMESTAMP(6) DEFAULT on null systimestamp NOT NULL,
  created_user        VARCHAR2(255 CHAR) DEFAULT on null user NOT NULL,
  updated_timestamp   TIMESTAMP(6),
  updated_user        VARCHAR2(255 CHAR)
, CONSTRAINT USERS_REQUEST_TYPES_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

prompt inserts into ad_sync_owner.AD_SYNC_STATUSES
INSERT INTO AD_SYNC_OWNER.AD_SYNC_USERS_REQUEST_TYPES (ID, REQUEST_TYPE_NAME, REQUEST_TYPE_DESCRIPTION) VALUES ('D','DROP_USER', 'DROP_USER');
INSERT INTO AD_SYNC_OWNER.AD_SYNC_USERS_REQUEST_TYPES (ID, REQUEST_TYPE_NAME, REQUEST_TYPE_DESCRIPTION) VALUES ('E','EXPIRE_PASSWORD', 'EXPIRE_PASSWORD');
INSERT INTO AD_SYNC_OWNER.AD_SYNC_USERS_REQUEST_TYPES (ID, REQUEST_TYPE_NAME, REQUEST_TYPE_DESCRIPTION) VALUES ('P','CHANGE_PASSWORD', 'CHANGE_PASSWORD');
INSERT INTO AD_SYNC_OWNER.AD_SYNC_USERS_REQUEST_TYPES (ID, REQUEST_TYPE_NAME, REQUEST_TYPE_DESCRIPTION) VALUES ('C','CREATE_USER', 'CREATE_USER');
INSERT INTO AD_SYNC_OWNER.AD_SYNC_USERS_REQUEST_TYPES (ID, REQUEST_TYPE_NAME, REQUEST_TYPE_DESCRIPTION) VALUES ('L','LOCK_USER', 'LOCK_USER');
INSERT INTO AD_SYNC_OWNER.AD_SYNC_USERS_REQUEST_TYPES (ID, REQUEST_TYPE_NAME, REQUEST_TYPE_DESCRIPTION) VALUES ('U','UNLOCK_USER', 'UNLOCK_USER');

commit;