prompt CREATE TABLE ad_sync_owner.AD_SYNC_STATUSES

CREATE TABLE AD_SYNC_OWNER.AD_SYNC_STATUSES (
  ID                 NUMBER NOT NULL
  ,STATUS_NAME        VARCHAR2(2000) NOT NULL
  ,STATUS_DESCRIPTION VARCHAR2(2000)
  ,CREATED_TIMESTAMP  TIMESTAMP(6) DEFAULT ON NULL SYSTIMESTAMP NOT NULL
  ,CREATED_USER       VARCHAR2(255 CHAR) DEFAULT ON NULL USER NOT NULL
  ,UPDATED_TIMESTAMP  TIMESTAMP(6)
  ,UPDATED_USER       VARCHAR2(255 CHAR)
  ,CONSTRAINT STATUSES_PK PRIMARY KEY ( ID ) ENABLE
);

prompt inserts into ad_sync_owner.AD_SYNC_STATUSES

INSERT INTO AD_SYNC_OWNER.AD_SYNC_STATUSES (
  ID
  ,STATUS_NAME
  ,STATUS_DESCRIPTION
) VALUES ( 1
          ,'NEW'
          ,'NEW' );

INSERT INTO AD_SYNC_OWNER.AD_SYNC_STATUSES (
  ID
  ,STATUS_NAME
  ,STATUS_DESCRIPTION
) VALUES ( 2
          ,'SYNC_STARTED'
          ,'SYNC_FINISHED' );

INSERT INTO AD_SYNC_OWNER.AD_SYNC_STATUSES (
  ID
  ,STATUS_NAME
  ,STATUS_DESCRIPTION
) VALUES ( 3
          ,'SYNC_FINISHED'
          ,'SYNC_FINISHED' );

INSERT INTO AD_SYNC_OWNER.AD_SYNC_STATUSES (
  ID
  ,STATUS_NAME
  ,STATUS_DESCRIPTION
) VALUES ( 22
          ,'USER_DROPPED'
          ,'USER_DROPPED' );

INSERT INTO AD_SYNC_OWNER.AD_SYNC_STATUSES (
  ID
  ,STATUS_NAME
  ,STATUS_DESCRIPTION
) VALUES ( 23
          ,'PASSWORD_EXPIRED'
          ,'PASSWORD_EXPIRED' );

INSERT INTO AD_SYNC_OWNER.AD_SYNC_STATUSES (
  ID
  ,STATUS_NAME
  ,STATUS_DESCRIPTION
) VALUES ( 24
          ,'PASSWORD_CHANGED'
          ,'PASSWORD_CHANGED' );

INSERT INTO AD_SYNC_OWNER.AD_SYNC_STATUSES (
  ID
  ,STATUS_NAME
  ,STATUS_DESCRIPTION
) VALUES ( 25
          ,'USER_UNLOCKED'
          ,'USER_UNLOCKED' );

INSERT INTO AD_SYNC_OWNER.AD_SYNC_STATUSES (
  ID
  ,STATUS_NAME
  ,STATUS_DESCRIPTION
) VALUES ( 26
          ,'USER_LOCKED'
          ,'USER_LOCKED' );

INSERT INTO AD_SYNC_OWNER.AD_SYNC_STATUSES (
  ID
  ,STATUS_NAME
  ,STATUS_DESCRIPTION
) VALUES ( 27
          ,'USER_BAD_PREFIX'
          ,'USER_BAD_PREFIX' );

INSERT INTO AD_SYNC_OWNER.AD_SYNC_STATUSES (
  ID
  ,STATUS_NAME
  ,STATUS_DESCRIPTION
) VALUES ( 28
          ,'USER_EXISTS'
          ,'USER_EXISTS' );

INSERT INTO AD_SYNC_OWNER.AD_SYNC_STATUSES (
  ID
  ,STATUS_NAME
  ,STATUS_DESCRIPTION
) VALUES ( 29
          ,'USER_CREATED'
          ,'USER_CREATED' );

INSERT INTO AD_SYNC_OWNER.AD_SYNC_STATUSES (
  ID
  ,STATUS_NAME
  ,STATUS_DESCRIPTION
) VALUES ( 32
          ,'GROUP_DROPPED'
          ,'GROUP_DROPPED' );

INSERT INTO AD_SYNC_OWNER.AD_SYNC_STATUSES (
  ID
  ,STATUS_NAME
  ,STATUS_DESCRIPTION
) VALUES ( 37
          ,'GROUP_BAD_PREFIX'
          ,'GROUP_BAD_PREFIX' );

INSERT INTO AD_SYNC_OWNER.AD_SYNC_STATUSES (
  ID
  ,STATUS_NAME
  ,STATUS_DESCRIPTION
) VALUES ( 38
          ,'GROUP_EXISTS'
          ,'GROUP_EXISTS' );

INSERT INTO AD_SYNC_OWNER.AD_SYNC_STATUSES (
  ID
  ,STATUS_NAME
  ,STATUS_DESCRIPTION
) VALUES ( 39
          ,'GROUP_CREATED'
          ,'GROUP_CREATED' );

INSERT INTO AD_SYNC_OWNER.AD_SYNC_STATUSES (
  ID
  ,STATUS_NAME
  ,STATUS_DESCRIPTION
) VALUES ( 42
          ,'GROUP_MEMBER_DROPPED'
          ,'GROUP_MEMBER_DROPPED' );

INSERT INTO AD_SYNC_OWNER.AD_SYNC_STATUSES (
  ID
  ,STATUS_NAME
  ,STATUS_DESCRIPTION
) VALUES ( 47
          ,'GROUP_OR_MEMBER_BAD_PREFIX'
          ,'GROUP_OR_MEMBER_BAD_PREFIX' );

INSERT INTO AD_SYNC_OWNER.AD_SYNC_STATUSES (
  ID
  ,STATUS_NAME
  ,STATUS_DESCRIPTION
) VALUES ( 48
          ,'GROUP_MEMBER_EXISTS'
          ,'GROUP_MEMBER_EXISTS' );

INSERT INTO AD_SYNC_OWNER.AD_SYNC_STATUSES (
  ID
  ,STATUS_NAME
  ,STATUS_DESCRIPTION
) VALUES ( 49
          ,'GROUP_MEMBER_CREATED'
          ,'GROUP_MEMBER_CREATED' );

INSERT INTO AD_SYNC_OWNER.AD_SYNC_STATUSES (
  ID
  ,STATUS_NAME
  ,STATUS_DESCRIPTION
) VALUES ( 99
          ,'SUCCESSS'
          ,'SUCCESSS' );

COMMIT;