prompt CREATE TABLE ad_sync_owner.AD_SYNC_GROUP_MEMBERS

CREATE TABLE ad_sync_owner.AD_SYNC_GROUP_MEMBERS
(
  ID NUMBER DEFAULT ad_sync_owner.AD_SYNC_GROUP_MEMBERS_seq.nextval NOT NULL 
, GROUPNAME VARCHAR2(1000) NOT NULL 
, MEMBER VARCHAR2(1000) NOT NULL 
, STATUS NUMBER DEFAULT 1 NOT NULL 
, PROCESS_TIMESTAMP timestamp ,
  LOAD_ID number,
	created_timestamp   TIMESTAMP(6) DEFAULT on null systimestamp NOT NULL,
  created_user        VARCHAR2(255 CHAR) DEFAULT on null user NOT NULL,
  updated_timestamp   TIMESTAMP(6),
  updated_user        VARCHAR2(255 CHAR)
, CONSTRAINT AD_SYNC_GROUP_MEMBERS_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

ALTER TABLE ad_sync_owner.AD_SYNC_GROUP_MEMBERS ADD CONSTRAINT AD_SYNC_GROUP_MEMBERS_FK1 FOREIGN KEY (STATUS) REFERENCES ad_sync_owner.AD_SYNC_STATUSES (ID) ENABLE;
