prompt CREATE TABLE ad_sync_owner.AD_SYNC_USERS_REQUEST_TYPES

CREATE TABLE AD_SYNC_OWNER.AD_SYNC_USERS_REQUEST_TYPES (
  ID                       CHAR(1) PRIMARY KEY
  ,REQUEST_TYPE_NAME        VARCHAR2(2000) NOT NULL
  ,REQUEST_TYPE_DESCRIPTION VARCHAR2(2000)
  ,CREATED_TIMESTAMP        TIMESTAMP(6) DEFAULT ON NULL SYSTIMESTAMP NOT NULL
  ,CREATED_USER             VARCHAR2(255 CHAR) DEFAULT ON NULL USER NOT NULL
  ,UPDATED_TIMESTAMP        TIMESTAMP(6)
  ,UPDATED_USER             VARCHAR2(255 CHAR)
);

prompt inserts into ad_sync_owner.AD_SYNC_STATUSES

INSERT INTO AD_SYNC_OWNER.AD_SYNC_USERS_REQUEST_TYPES (
  ID
  ,REQUEST_TYPE_NAME
  ,REQUEST_TYPE_DESCRIPTION
) VALUES ( 'D'
          ,'DROP_USER'
          ,'DROP_USER' );

INSERT INTO AD_SYNC_OWNER.AD_SYNC_USERS_REQUEST_TYPES (
  ID
  ,REQUEST_TYPE_NAME
  ,REQUEST_TYPE_DESCRIPTION
) VALUES ( 'E'
          ,'EXPIRE_PASSWORD'
          ,'EXPIRE_PASSWORD' );

INSERT INTO AD_SYNC_OWNER.AD_SYNC_USERS_REQUEST_TYPES (
  ID
  ,REQUEST_TYPE_NAME
  ,REQUEST_TYPE_DESCRIPTION
) VALUES ( 'P'
          ,'CHANGE_PASSWORD'
          ,'CHANGE_PASSWORD' );

INSERT INTO AD_SYNC_OWNER.AD_SYNC_USERS_REQUEST_TYPES (
  ID
  ,REQUEST_TYPE_NAME
  ,REQUEST_TYPE_DESCRIPTION
) VALUES ( 'C'
          ,'CREATE_USER'
          ,'CREATE_USER' );

INSERT INTO AD_SYNC_OWNER.AD_SYNC_USERS_REQUEST_TYPES (
  ID
  ,REQUEST_TYPE_NAME
  ,REQUEST_TYPE_DESCRIPTION
) VALUES ( 'L'
          ,'LOCK_USER'
          ,'LOCK_USER' );

INSERT INTO AD_SYNC_OWNER.AD_SYNC_USERS_REQUEST_TYPES (
  ID
  ,REQUEST_TYPE_NAME
  ,REQUEST_TYPE_DESCRIPTION
) VALUES ( 'U'
          ,'UNLOCK_USER'
          ,'UNLOCK_USER' );

COMMIT;