prompt CREATE TABLE ad_sync_owner.AD_SYNC_STATUSES 
CREATE TABLE ad_sync_owner.AD_SYNC_STATUSES 
(
  ID NUMBER NOT NULL 
, STATUS_NAME VARCHAR2(2000) NOT NULL 
, STATUS_DESCRIPTION VARCHAR2(2000) ,
	created_timestamp   TIMESTAMP(6) DEFAULT on null systimestamp NOT NULL,
  created_user        VARCHAR2(255 CHAR) DEFAULT on null user NOT NULL,
  updated_timestamp   TIMESTAMP(6),
  updated_user        VARCHAR2(255 CHAR)
, CONSTRAINT STATUSES_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

prompt inserts into ad_sync_owner.AD_SYNC_STATUSES
INSERT INTO AD_SYNC_OWNER.AD_SYNC_STATUSES (ID, STATUS_NAME, STATUS_DESCRIPTION) VALUES (1,'NEW', 'NEW');
INSERT INTO AD_SYNC_OWNER.AD_SYNC_STATUSES (ID, STATUS_NAME, STATUS_DESCRIPTION) VALUES (2,'SYNC_STARTED', 'SYNC_FINISHED');
INSERT INTO AD_SYNC_OWNER.AD_SYNC_STATUSES (ID, STATUS_NAME, STATUS_DESCRIPTION) VALUES (3,'SYNC_FINISHED', 'SYNC_FINISHED');

INSERT INTO AD_SYNC_OWNER.AD_SYNC_STATUSES (ID, STATUS_NAME, STATUS_DESCRIPTION) VALUES (23, 'PASSWORD_EXPIRED', 'PASSWORD_EXPIRED');
INSERT INTO AD_SYNC_OWNER.AD_SYNC_STATUSES (ID, STATUS_NAME, STATUS_DESCRIPTION) VALUES (24, 'PASSWORD_CHANGED', 'PASSWORD_CHANGED');
INSERT INTO AD_SYNC_OWNER.AD_SYNC_STATUSES (ID, STATUS_NAME, STATUS_DESCRIPTION) VALUES (25, 'USER_UNLOCKED', 'USER_UNLOCKED');
INSERT INTO AD_SYNC_OWNER.AD_SYNC_STATUSES (ID, STATUS_NAME, STATUS_DESCRIPTION) VALUES (26, 'USER_LOCKED', 'USER_LOCKED');
INSERT INTO AD_SYNC_OWNER.AD_SYNC_STATUSES (ID, STATUS_NAME, STATUS_DESCRIPTION) VALUES (27, 'USER_BAD_PREFIX', 'USER_BAD_PREFIX');
INSERT INTO AD_SYNC_OWNER.AD_SYNC_STATUSES (ID, STATUS_NAME, STATUS_DESCRIPTION) VALUES (28, 'USER_EXISTS', 'USER_EXISTS');
INSERT INTO AD_SYNC_OWNER.AD_SYNC_STATUSES (ID, STATUS_NAME, STATUS_DESCRIPTION) VALUES (29, 'USER_CREATED', 'USER_CREATED');

INSERT INTO AD_SYNC_OWNER.AD_SYNC_STATUSES (ID, STATUS_NAME, STATUS_DESCRIPTION) VALUES (99, 'SUCCESSS', 'SUCCESSS');
commit;