prompt CREATE TABLE ad_sync_owner.ad_sync_users 

CREATE TABLE ad_sync_owner.AD_SYNC_USERS 
(
  ID NUMBER DEFAULT ad_sync_owner.ad_sync_users_seq.nextval NOT NULL 
, USERNAME VARCHAR2(1000) NOT NULL 
, REQUESTED_OPERATION CHAR(1) DEFAULT 'C' NOT NULL  
, PASSWORD VARCHAR2(100)
, PASSWORD_FILE VARCHAR2(100)
, STATUS NUMBER DEFAULT 1 NOT NULL 
, PROCESS_TIMESTAMP timestamp ,
  LOAD_ID number,
  created_timestamp   TIMESTAMP(6) DEFAULT on null systimestamp NOT NULL,
  created_user        VARCHAR2(255 CHAR) DEFAULT on null user NOT NULL,
  updated_timestamp   TIMESTAMP(6),
  updated_user        VARCHAR2(255 CHAR)
, CONSTRAINT ad_sync_users_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

ALTER TABLE ad_sync_owner.AD_SYNC_USERS ADD CONSTRAINT AD_SYNC_USERS_FK1 FOREIGN KEY (STATUS) REFERENCES ad_sync_owner.AD_SYNC_STATUSES (ID) ENABLE;
ALTER TABLE ad_sync_owner.AD_SYNC_USERS ADD CONSTRAINT AD_SYNC_USERS_FK2 FOREIGN KEY (REQUESTED_OPERATION) REFERENCES ad_sync_owner.AD_SYNC_USERS_REQUEST_TYPES (ID) ENABLE;