prompt CREATE TABLE ad_sync_owner.AD_SYNC_LOG_TABLE

CREATE TABLE AD_SYNC_OWNER.AD_SYNC_LOG_TABLE (
  LOG_ID            INTEGER NOT NULL PRIMARY KEY
  ,PROCESS_RUN_ID    INTEGER
  ,LOG_TYPE          INTEGER
    REFERENCES AD_SYNC_OWNER.AD_SYNC_LOG_TABLE_TYPE ( ID )
  ,LOG_SRC           VARCHAR2(4000 CHAR)
  ,LOG_CODE          INTEGER
  ,LOG_MSG           VARCHAR2(4000 CHAR) NOT NULL
  ,LOG_TIMESTAMP     TIMESTAMP WITH TIME ZONE
  ,CREATED_TIMESTAMP TIMESTAMP(6) DEFAULT ON NULL SYSTIMESTAMP NOT NULL ENABLE
  ,CREATED_USER      VARCHAR2(255 CHAR) DEFAULT ON NULL USER NOT NULL ENABLE
  ,UPDATED_TIMESTAMP TIMESTAMP(6)
  ,UPDATED_USER      VARCHAR2(255 CHAR)
);