prompt CREATE TABLE ad_sync_owner.AD_SYNC_HISTORY 

CREATE TABLE ad_sync_owner.AD_SYNC_HISTORY 
(
  ID NUMBER DEFAULT ad_sync_owner.AD_SYNC_HISTORY_SEQ.nextval NOT NULL 
, LOAD_ID number -- ad_sync_owner.AD_SYNC_LOAD_SEQ.nextval NOT NULL
, LOAD_TYPE char(1)
, SYNC_STATUS VARCHAR2(2000) NOT NULL 
, created_timestamp   TIMESTAMP(6) DEFAULT on null systimestamp NOT NULL,
  created_user        VARCHAR2(255 CHAR) DEFAULT on null user NOT NULL,
  updated_timestamp   TIMESTAMP(6),
  updated_user        VARCHAR2(255 CHAR)
, CONSTRAINT AD_SYNCHRONIZE_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

ALTER TABLE ad_sync_owner.AD_SYNC_HISTORY ADD CONSTRAINT AD_SYNC_HISTORY_FK1 FOREIGN KEY (SYNC_STATUS) REFERENCES ad_sync_owner.AD_SYNC_STATUSES (ID) ENABLE;
ALTER TABLE ad_sync_owner.AD_SYNC_HISTORY ADD CONSTRAINT AD_SYNC_HISTORY_FK2 FOREIGN KEY (LOAD_TYPE) REFERENCES ad_sync_owner.AD_SYNC_HISTORY_LOAD_TYPESES (ID) ENABLE;