prompt CREATE TABLE ad_sync_owner.AD_SYNC_GROUP_TABLESPACE_QUOTAS

CREATE TABLE AD_SYNC_OWNER.AD_SYNC_GROUP_TABLESPACE_QUOTAS (
  ID                  NUMBER DEFAULT AD_SYNC_OWNER.AD_SYNC_GROUP_TABLESPACE_QUOTAS_SEQ.NEXTVAL NOT NULL
  ,GROUPNAME           VARCHAR2(1000) NOT NULL
  ,TABLESPACE              VARCHAR2(1000) NOT NULL
  ,QUOTA               VARCHAR2(100)  NOT NULL
  ,CREATED_TIMESTAMP   TIMESTAMP(6) DEFAULT ON NULL SYSTIMESTAMP NOT NULL
  ,CREATED_USER        VARCHAR2(255 CHAR) DEFAULT ON NULL USER NOT NULL
  ,UPDATED_TIMESTAMP   TIMESTAMP(6)
  ,UPDATED_USER        VARCHAR2(255 CHAR)
  ,CONSTRAINT AD_SYNC_GROUP_TABLESPACE_QUOTAS_PK PRIMARY KEY ( ID ) ENABLE
);
