prompt CREATE TABLE ad_sync_owner.AD_SYNC_PARAMETERS

CREATE TABLE AD_SYNC_OWNER.AD_SYNC_PARAMETERS (
  PARAMETER_NAME VARCHAR2(100 CHAR) PRIMARY KEY,
  PARAMETER_VALUE VARCHAR2(200 CHAR),
  DESCRIPTION VARCHAR2(4000 CHAR),
  CREATED_TIMESTAMP TIMESTAMP(6) DEFAULT ON NULL SYSTIMESTAMP NOT NULL,
  CREATED_USER VARCHAR2(255 CHAR) DEFAULT ON NULL USER NOT NULL,
  UPDATED_TIMESTAMP TIMESTAMP(6),
  UPDATED_USER VARCHAR2(255 CHAR)
) ORGANIZATION INDEX NOLOGGING INCLUDING PARAMETER_VALUE OVERFLOW STORAGE (
  BUFFER_POOL KEEP
);

INSERT INTO AD_SYNC_OWNER.AD_SYNC_PARAMETERS (
  PARAMETER_NAME,
  PARAMETER_VALUE,
  DESCRIPTION
) VALUES (
  'LOG_WARNING',
  '1',
  ''
);

INSERT INTO AD_SYNC_OWNER.AD_SYNC_PARAMETERS (
  PARAMETER_NAME,
  PARAMETER_VALUE,
  DESCRIPTION
) VALUES (
  'LOG_INFO',
  '1',
  ''
);

INSERT INTO AD_SYNC_OWNER.AD_SYNC_PARAMETERS (
  PARAMETER_NAME,
  PARAMETER_VALUE,
  DESCRIPTION
) VALUES (
  'STORE_USER_PASSWORD_IN_FILE',
  '1',
  '1 means yes'
);

INSERT INTO AD_SYNC_OWNER.AD_SYNC_PARAMETERS (
  PARAMETER_NAME,
  PARAMETER_VALUE,
  DESCRIPTION
) VALUES (
  'STORE_USER_PASSWORD_IN_FILE_DIRECTORY',
  '&user_pass_directory_name.',
  'directory object name'
);

INSERT INTO AD_SYNC_OWNER.AD_SYNC_PARAMETERS (
  PARAMETER_NAME,
  PARAMETER_VALUE,
  DESCRIPTION
) VALUES (
  'STORE_USER_PASSWORD_IN_TABLE',
  '1',
  '1 means yes'
);

INSERT INTO AD_SYNC_OWNER.AD_SYNC_PARAMETERS (
  PARAMETER_NAME,
  PARAMETER_VALUE,
  DESCRIPTION
) VALUES (
  'USER_ACCOUNT_LOCK_STATUS',
  'unlock',
  'unlock or lock'
);

INSERT INTO AD_SYNC_OWNER.AD_SYNC_PARAMETERS (
  PARAMETER_NAME,
  PARAMETER_VALUE,
  DESCRIPTION
) VALUES (
  'USER_TABLESPACE',
  'users',
  ''
);

INSERT INTO AD_SYNC_OWNER.AD_SYNC_PARAMETERS (
  PARAMETER_NAME,
  PARAMETER_VALUE,
  DESCRIPTION
) VALUES (
  'USER_TEMP_TABLESPACE',
  'temp',
  ''
);

INSERT INTO AD_SYNC_OWNER.AD_SYNC_PARAMETERS (
  PARAMETER_NAME,
  PARAMETER_VALUE,
  DESCRIPTION
) VALUES (
  'USERNAME_PREFIX',
  '&username_prefix.',
  ''
);

INSERT INTO AD_SYNC_OWNER.AD_SYNC_PARAMETERS (
  PARAMETER_NAME,
  PARAMETER_VALUE,
  DESCRIPTION
) VALUES (
  'GROUPNAME_PREFIX',
  '&groupname_prefix.',
  ''
);

INSERT INTO AD_SYNC_OWNER.AD_SYNC_PARAMETERS (
  PARAMETER_NAME,
  PARAMETER_VALUE,
  DESCRIPTION
) VALUES (
  'SYNC_USERS_LOCK_INSTEAD_OF_DROP',
  '1',
  '1 means yes'
);

INSERT INTO AD_SYNC_OWNER.AD_SYNC_PARAMETERS (
  PARAMETER_NAME,
  PARAMETER_VALUE,
  DESCRIPTION
) VALUES (
  'SYNC_USERS_PROCESS_DROP',
  '1',
  '1 means yes'
);

INSERT INTO AD_SYNC_OWNER.AD_SYNC_PARAMETERS (
  PARAMETER_NAME,
  PARAMETER_VALUE,
  DESCRIPTION
) VALUES (
  'SYNC_GROUPS_PROCESS_DROP',
  '1',
  '1 means yes'
);

INSERT INTO AD_SYNC_OWNER.AD_SYNC_PARAMETERS (
  PARAMETER_NAME,
  PARAMETER_VALUE,
  DESCRIPTION
) VALUES (
  'SYNC_GROUP_MEMBERS_PROCESS_DROP',
  '1',
  '1 means yes'
);

COMMIT;