prompt CREATE TABLE ad_sync_owner.AD_SYNC_HISTORY

CREATE TABLE AD_SYNC_OWNER.AD_SYNC_HISTORY (
  ID NUMBER DEFAULT AD_SYNC_OWNER.AD_SYNC_HISTORY_SEQ.NEXTVAL NOT NULL,
  LOAD_ID NUMBER -- ad_sync_owner.AD_SYNC_LOAD_SEQ.nextval NOT NULL
,
  LOAD_TYPE CHAR(1),
  SYNC_STATUS NUMBER NOT NULL,
  CREATED_TIMESTAMP TIMESTAMP(6) DEFAULT ON NULL SYSTIMESTAMP NOT NULL,
  CREATED_USER VARCHAR2(255 CHAR) DEFAULT ON NULL USER NOT NULL,
  UPDATED_TIMESTAMP TIMESTAMP(6),
  UPDATED_USER VARCHAR2(255 CHAR),
  CONSTRAINT AD_SYNCHRONIZE_PK PRIMARY KEY ( ID ) ENABLE
);

ALTER TABLE AD_SYNC_OWNER.AD_SYNC_HISTORY
  ADD CONSTRAINT AD_SYNC_HISTORY_FK1 FOREIGN KEY (
    SYNC_STATUS
  )
    REFERENCES AD_SYNC_OWNER.AD_SYNC_STATUSES (
      ID
    ) ENABLE;

ALTER TABLE AD_SYNC_OWNER.AD_SYNC_HISTORY
  ADD CONSTRAINT AD_SYNC_HISTORY_FK2 FOREIGN KEY (
    LOAD_TYPE
  )
    REFERENCES AD_SYNC_OWNER.AD_SYNC_HISTORY_LOAD_TYPES (
      ID
    ) ENABLE;