prompt CREATE TABLE ad_sync_owner.ad_sync_users

CREATE TABLE AD_SYNC_OWNER.AD_SYNC_USERS (
  ID                  NUMBER DEFAULT AD_SYNC_OWNER.AD_SYNC_USERS_SEQ.NEXTVAL NOT NULL
  ,USERNAME            VARCHAR2(1000) NOT NULL
  ,REQUESTED_OPERATION CHAR(1) DEFAULT 'C' NOT NULL
  ,PASSWORD            VARCHAR2(100)
  ,PASSWORD_FILE       VARCHAR2(100)
  ,STATUS              NUMBER DEFAULT 1 NOT NULL
  ,PROCESS_TIMESTAMP   TIMESTAMP
  ,LOAD_ID             NUMBER
  ,CREATED_TIMESTAMP   TIMESTAMP(6) DEFAULT ON NULL SYSTIMESTAMP NOT NULL
  ,CREATED_USER        VARCHAR2(255 CHAR) DEFAULT ON NULL USER NOT NULL
  ,UPDATED_TIMESTAMP   TIMESTAMP(6)
  ,UPDATED_USER        VARCHAR2(255 CHAR)
  ,CONSTRAINT AD_SYNC_USERS_PK PRIMARY KEY ( ID ) ENABLE
);

ALTER TABLE AD_SYNC_OWNER.AD_SYNC_USERS
  ADD CONSTRAINT AD_SYNC_USERS_FK1
    FOREIGN KEY ( STATUS )
      REFERENCES AD_SYNC_OWNER.AD_SYNC_STATUSES ( ID )
    ENABLE;

ALTER TABLE AD_SYNC_OWNER.AD_SYNC_USERS
  ADD CONSTRAINT AD_SYNC_USERS_FK2
    FOREIGN KEY ( REQUESTED_OPERATION )
      REFERENCES AD_SYNC_OWNER.AD_SYNC_USERS_REQUEST_TYPES ( ID )
    ENABLE;