prompt CREATE TABLE ad_sync_owner.AD_SYNC_HISTORY_LOAD_TYPES

CREATE TABLE AD_SYNC_OWNER.AD_SYNC_HISTORY_LOAD_TYPES (
  ID CHAR(1) NOT NULL,
  LOAD_TYPE_NAME VARCHAR2(2000) NOT NULL,
  LOAD_TYPE_DESCRIPTION VARCHAR2(2000),
  CREATED_TIMESTAMP TIMESTAMP(6) DEFAULT ON NULL SYSTIMESTAMP NOT NULL,
  CREATED_USER VARCHAR2(255 CHAR) DEFAULT ON NULL USER NOT NULL,
  UPDATED_TIMESTAMP TIMESTAMP(6),
  UPDATED_USER VARCHAR2(255 CHAR),
  CONSTRAINT USERS_REQUEST_TYPES_PK PRIMARY KEY ( ID ) ENABLE
);

prompt inserts into ad_sync_owner.AD_SYNC_HISTORY_LOAD_TYPES

INSERT INTO AD_SYNC_OWNER.AD_SYNC_HISTORY_LOAD_TYPES (
  ID,
  LOAD_TYPE_NAME,
  LOAD_TYPE_DESCRIPTION
) VALUES (
  'M',
  'MANAGE_USERS',
  'MANAGE_USERS'
);

INSERT INTO AD_SYNC_OWNER.AD_SYNC_HISTORY_LOAD_TYPES (
  ID,
  LOAD_TYPE_NAME,
  LOAD_TYPE_DESCRIPTION
) VALUES (
  'R',
  'RELOAD',
  'RELOAD ALL USERS, GROUPS and GRPUP MEMBERS'
);

COMMIT;