prompt CREATE TABLE ad_sync_owner.AD_SYNC_HISTORY_LOAD_TYPES 
CREATE TABLE ad_sync_owner.AD_SYNC_HISTORY_LOAD_TYPES 
(
  ID char(1) NOT NULL 
, LOAD_TYPE_NAME VARCHAR2(2000) NOT NULL 
, LOAD_TYPE_DESCRIPTION VARCHAR2(2000) ,
	created_timestamp   TIMESTAMP(6) DEFAULT on null systimestamp NOT NULL,
  created_user        VARCHAR2(255 CHAR) DEFAULT on null user NOT NULL,
  updated_timestamp   TIMESTAMP(6),
  updated_user        VARCHAR2(255 CHAR)
, CONSTRAINT USERS_REQUEST_TYPES_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

prompt inserts into ad_sync_owner.AD_SYNC_HISTORY_LOAD_TYPES
INSERT INTO AD_SYNC_OWNER.AD_SYNC_HISTORY_LOAD_TYPES (ID, LOAD_TYPE_NAME, LOAD_TYPE_DESCRIPTION) VALUES ('M','MANAGE_USERS', 'MANAGE_USERS');
INSERT INTO AD_SYNC_OWNER.AD_SYNC_HISTORY_LOAD_TYPES (ID, LOAD_TYPE_NAME, LOAD_TYPE_DESCRIPTION) VALUES ('R','RELOAD', 'RELOAD ALL USERS, GROUPS and GRPUP MEMBERS');

commit;