prompt CREATE TABLE ad_sync_owner.AD_SYNC_LOG_TABLE_TYPE

CREATE TABLE AD_SYNC_OWNER.AD_SYNC_LOG_TABLE_TYPE (
  ID INTEGER NOT NULL PRIMARY KEY,
  DESCRIPTION VARCHAR2 (100 CHAR),
  CREATED_TIMESTAMP TIMESTAMP(6) DEFAULT ON NULL SYSTIMESTAMP NOT NULL,
  CREATED_USER VARCHAR2(255 CHAR) DEFAULT ON NULL USER NOT NULL,
  UPDATED_TIMESTAMP TIMESTAMP(6),
  UPDATED_USER VARCHAR2(255 CHAR)
);

PROMPT LOADING ad_sync_owner.AD_SYNC_LOG_TABLE_TYPE

INSERT INTO AD_SYNC_OWNER.AD_SYNC_LOG_TABLE_TYPE (
  ID,
  DESCRIPTION
) VALUES (
  0,
  'ERROR'
);

INSERT INTO AD_SYNC_OWNER.AD_SYNC_LOG_TABLE_TYPE (
  ID,
  DESCRIPTION
) VALUES (
  1,
  'WARRNING'
);

INSERT INTO AD_SYNC_OWNER.AD_SYNC_LOG_TABLE_TYPE (
  ID,
  DESCRIPTION
) VALUES (
  2,
  'INFO'
);

COMMIT;

PROMPT ad_sync_owner.AD_SYNC_LOG_TABLE_TYPE - 3 rows created.