   set serveroutput on;

DECLARE
  V_START_TIMESTAMP TIMESTAMP;
  V_END_TIMESTAMP   TIMESTAMP;
  V_LOAD_ID         NUMBER;
  V_PROCESS_RUN     NUMBER := AD_SYNC_OWNER.AD_SYNC_PROCESS_RUN_SEQ.NEXTVAL;
BEGIN
  SELECT CREATED_TIMESTAMP
        ,LOAD_ID
    INTO
    V_START_TIMESTAMP
  ,V_LOAD_ID
    FROM AD_SYNC_OWNER.AD_SYNC_HISTORY
   WHERE SYNC_STATUS = 2
     AND CREATED_TIMESTAMP = (
    SELECT MAX(CREATED_TIMESTAMP)
      FROM AD_SYNC_OWNER.AD_SYNC_HISTORY
     WHERE SYNC_STATUS = 2
  );
  SELECT MAX(CREATED_TIMESTAMP)
    INTO V_END_TIMESTAMP
    FROM AD_SYNC_OWNER.AD_SYNC_HISTORY
   WHERE SYNC_STATUS = 3;
  AD_SYNC_OWNER.AD_SYNC_PROCESS_USERS.MARK_EXISTING_USERS(
    V_START_TIMESTAMP
   ,V_END_TIMESTAMP
   ,V_PROCESS_RUN
   ,V_LOAD_ID
  );
  AD_SYNC_OWNER.AD_SYNC_PROCESS_USERS.ADD_USERS(
    V_START_TIMESTAMP
   ,V_END_TIMESTAMP
   ,V_PROCESS_RUN
   ,V_LOAD_ID
  );
  AD_SYNC_OWNER.AD_SYNC_PROCESS_USERS.LOCK_USERS(
    V_START_TIMESTAMP
   ,V_END_TIMESTAMP
   ,V_PROCESS_RUN
   ,V_LOAD_ID
  );
  AD_SYNC_OWNER.AD_SYNC_PROCESS_USERS.UNLOCK_USERS(
    V_START_TIMESTAMP
   ,V_END_TIMESTAMP
   ,V_PROCESS_RUN
   ,V_LOAD_ID
  );
  AD_SYNC_OWNER.AD_SYNC_PROCESS_USERS.CHANGE_PASSWORD(
    V_START_TIMESTAMP
   ,V_END_TIMESTAMP
   ,V_PROCESS_RUN
   ,V_LOAD_ID
  );
  AD_SYNC_OWNER.AD_SYNC_PROCESS_USERS.EXPIRE_PASSWORD(
    V_START_TIMESTAMP
   ,V_END_TIMESTAMP
   ,V_PROCESS_RUN
   ,V_LOAD_ID
  );
  AD_SYNC_OWNER.AD_SYNC_PROCESS_USERS.DROP_USERS(
    V_START_TIMESTAMP
   ,V_END_TIMESTAMP
   ,V_PROCESS_RUN
   ,V_LOAD_ID
  );
  AD_SYNC_OWNER.AD_SYNC_PROCESS_GROUPS.ADD_GROUPS(
    V_START_TIMESTAMP
   ,V_END_TIMESTAMP
   ,V_PROCESS_RUN
   ,V_LOAD_ID
  );
  AD_SYNC_OWNER.AD_SYNC_PROCESS_GROUPS.MARK_EXISTING_GROUPS(
    V_START_TIMESTAMP
   ,V_END_TIMESTAMP
   ,V_PROCESS_RUN
   ,V_LOAD_ID
  );
  AD_SYNC_OWNER.AD_SYNC_PROCESS_GROUP_MEMBERS.ADD_GROUP_MEMBERS(
    V_START_TIMESTAMP
   ,V_END_TIMESTAMP
   ,V_PROCESS_RUN
   ,V_LOAD_ID
  );
END;
/