    prompt ad_sync_interface_grants

    GRANT CONNECT TO AD_SYNC_INTERFACE;

    GRANT EXECUTE ON AD_SYNC_OWNER.AD_SYNC_LOAD TO AD_SYNC_INTERFACE;

    GRANT READ ON AD_SYNC_OWNER.AD_SYNC_USERS TO AD_SYNC_INTERFACE;

    GRANT READ ON AD_SYNC_OWNER.AD_SYNC_STATUSES TO AD_SYNC_INTERFACE;

    GRANT READ ON AD_SYNC_OWNER.AD_SYNC_PROCESSING_STATUS_USERS TO AD_SYNC_INTERFACE;

    GRANT READ ON AD_SYNC_OWNER.AD_SYNC_MANAGED_USERS TO AD_SYNC_INTERFACE;

    GRANT READ ON AD_SYNC_OWNER.AD_SYNC_MANAGED_GROUPS TO AD_SYNC_INTERFACE;

    GRANT READ ON AD_SYNC_OWNER.AD_SYNC_MANAGED_GROUP_MEMBERS TO AD_SYNC_INTERFACE;

    GRANT SELECT ON SYS.DBA_USERS TO AD_SYNC_INTERFACE;

    GRANT SELECT ON SYS.DBA_ROLES TO AD_SYNC_INTERFACE;

    GRANT SELECT ON SYS.DBA_ROLE_PRIVS TO AD_SYNC_INTERFACE;

    GRANT SELECT ON SYS.ROLE_ROLE_PRIVS TO AD_SYNC_INTERFACE;