prompt ad_sync_owner

DROP USER AD_SYNC_OWNER CASCADE;

prompt CREATE USER ad_sync_owner

-- USER SQL
CREATE USER AD_SYNC_OWNER IDENTIFIED BY &AD_SYNC_OWNER_PASSWD.
DEFAULT TABLESPACE &AD_SYNC_OWNER_TABLESPACE.
TEMPORARY TABLESPACE &TEMP_TABLESPACE.;

-- QUOTAS
ALTER USER AD_SYNC_OWNER QUOTA UNLIMITED ON &AD_SYNC_OWNER_TABLESPACE.;

-- SYSTEM PRIVILEGES
GRANT CONNECT TO AD_SYNC_OWNER;

GRANT CREATE TABLE TO AD_SYNC_OWNER;

GRANT CREATE PROCEDURE TO AD_SYNC_OWNER;

GRANT CREATE VIEW TO AD_SYNC_OWNER;

GRANT CREATE SEQUENCE TO AD_SYNC_OWNER;

GRANT INHERIT PRIVILEGES ON USER SYS TO AD_SYNC_OWNER;

GRANT SELECT ON SYS.DBA_USERS TO AD_SYNC_OWNER WITH GRANT OPTION;

GRANT SELECT ON SYS.DBA_ROLES TO AD_SYNC_OWNER WITH GRANT OPTION;

GRANT SELECT ON SYS.DBA_ROLE_PRIVS TO AD_SYNC_OWNER WITH GRANT OPTION;

GRANT SELECT ON SYS.ROLE_ROLE_PRIVS TO AD_SYNC_OWNER WITH GRANT OPTION;

GRANT READ ON DBA_OBJECTS TO AD_SYNC_OWNER;