prompt ad_sync_owner_grants

-- SYSTEM PRIVILEGES
GRANT CONNECT TO AD_SYNC_OWNER;

GRANT CREATE TABLE TO AD_SYNC_OWNER;

GRANT CREATE PROCEDURE TO AD_SYNC_OWNER;

GRANT CREATE VIEW TO AD_SYNC_OWNER;

GRANT CREATE SEQUENCE TO AD_SYNC_OWNER;

GRANT INHERIT PRIVILEGES ON USER SYS TO AD_SYNC_OWNER;

GRANT CREATE ROLE TO AD_SYNC_OWNER;

GRANT GRANT ANY OBJECT PRIVILEGE TO AD_SYNC_OWNER;

GRANT ALTER USER TO AD_SYNC_OWNER;

GRANT CREATE USER TO AD_SYNC_OWNER;

GRANT ALTER ANY ROLE TO AD_SYNC_OWNER;

GRANT GRANT ANY PRIVILEGE TO AD_SYNC_OWNER;

GRANT DROP USER TO AD_SYNC_OWNER;

GRANT DROP ANY ROLE TO AD_SYNC_OWNER;

GRANT GRANT ANY ROLE TO AD_SYNC_OWNER;

GRANT SELECT ON SYS.DBA_USERS TO AD_SYNC_OWNER WITH GRANT OPTION;

GRANT SELECT ON SYS.DBA_ROLES TO AD_SYNC_OWNER WITH GRANT OPTION;

GRANT SELECT ON SYS.DBA_ROLE_PRIVS TO AD_SYNC_OWNER WITH GRANT OPTION;

GRANT SELECT ON SYS.ROLE_ROLE_PRIVS TO AD_SYNC_OWNER WITH GRANT OPTION;