CREATE PROFILE AD_SYNC_DEFAULT_PROFILE
LIMIT
    COMPOSITE_LIMIT DEFAULT
    SESSIONS_PER_USER DEFAULT
    CPU_PER_SESSION DEFAULT
    CPU_PER_CALL DEFAULT
    LOGICAL_READS_PER_SESSION DEFAULT
    LOGICAL_READS_PER_CALL DEFAULT
    IDLE_TIME 15
    CONNECT_TIME DEFAULT
    PRIVATE_SGA DEFAULT
    FAILED_LOGIN_ATTEMPTS 3
    PASSWORD_LIFE_TIME 90
    PASSWORD_REUSE_TIME 365
    PASSWORD_REUSE_MAX 10
    PASSWORD_VERIFY_FUNCTION AD_SYNC_DEFAULT_PASSWORD_VERIFY_FUNCTION
    PASSWORD_LOCK_TIME UNLIMITED
    PASSWORD_GRACE_TIME 5